// <auto-generated />
using System;
using KvizHub.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KvizHub.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516103452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KvizHub.Repository.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 101,
                            Text = "1937"
                        },
                        new
                        {
                            Id = 1002,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 101,
                            Text = "1939"
                        },
                        new
                        {
                            Id = 1003,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 101,
                            Text = "1941"
                        },
                        new
                        {
                            Id = 1004,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 101,
                            Text = "1945"
                        },
                        new
                        {
                            Id = 1005,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 102,
                            Text = "Rim"
                        },
                        new
                        {
                            Id = 1006,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 102,
                            Text = "Atina"
                        },
                        new
                        {
                            Id = 1007,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 102,
                            Text = "Konstantinopolj"
                        },
                        new
                        {
                            Id = 1008,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 102,
                            Text = "Aleksandrija"
                        },
                        new
                        {
                            Id = 1009,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 103,
                            Text = "Ivo Andrić"
                        },
                        new
                        {
                            Id = 1010,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 103,
                            Text = "Meša Selimović"
                        },
                        new
                        {
                            Id = 1017,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 103,
                            Text = "Branko Ćopić"
                        },
                        new
                        {
                            Id = 1018,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 103,
                            Text = "Miloš Crnjanski"
                        },
                        new
                        {
                            Id = 1011,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 104,
                            Text = "Toronto"
                        },
                        new
                        {
                            Id = 1012,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 104,
                            Text = "Vankuver"
                        },
                        new
                        {
                            Id = 1013,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 104,
                            Text = "Otava"
                        },
                        new
                        {
                            Id = 1014,
                            IsCorrect = false,
                            OrderIndex = 0,
                            QuestionId = 104,
                            Text = "Montreal"
                        },
                        new
                        {
                            Id = 1015,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 105,
                            Text = "Rusija"
                        },
                        new
                        {
                            Id = 1016,
                            IsCorrect = true,
                            OrderIndex = 0,
                            QuestionId = 105,
                            Text = "rusija"
                        });
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderIndex = 1,
                            Points = 10,
                            QuizId = 10,
                            Text = "Koje godine je počeo Drugi svetski rat?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderIndex = 2,
                            Points = 10,
                            QuizId = 10,
                            Text = "Koji grad je bio glavni grad Vizantijskog carstva?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderIndex = 3,
                            Points = 5,
                            QuizId = 10,
                            Text = "Ko je napisao roman 'Na Drini ćuprija'?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderIndex = 1,
                            Points = 10,
                            QuizId = 11,
                            Text = "Koji je glavni grad Kanade?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderIndex = 2,
                            Points = 15,
                            QuizId = 11,
                            Text = "Koja je najveća država na svetu po površini?",
                            Type = "FillInTheBlank"
                        });
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kviz iz istorije i književnosti",
                            Difficulty = "Beginner",
                            IsActive = true,
                            TimeLimitMinutes = 15,
                            Title = "Istorijski izazov"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pitanja o državama i kontinentima",
                            Difficulty = "Intermediate",
                            IsActive = true,
                            TimeLimitMinutes = 20,
                            Title = "Geografija sveta"
                        });
                });

            modelBuilder.Entity("KvizHub.Repository.Models.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TimeSpent")
                        .HasColumnType("time");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.QuizCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("QuizCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pitanja iz različitih oblasti",
                            IsActive = true,
                            Name = "Opšte znanje"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Istorijska pitanja",
                            IsActive = true,
                            Name = "Istorija"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Geografska pitanja",
                            IsActive = true,
                            Name = "Geografija"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Naučna pitanja",
                            IsActive = true,
                            Name = "Nauka"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sportska pitanja",
                            IsActive = true,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "IT i tehnološka pitanja",
                            IsActive = true,
                            Name = "Tehnologija"
                        });
                });

            modelBuilder.Entity("KvizHub.Repository.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswerIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Answer", b =>
                {
                    b.HasOne("KvizHub.Repository.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Question", b =>
                {
                    b.HasOne("KvizHub.Repository.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Quiz", b =>
                {
                    b.HasOne("KvizHub.Repository.Models.QuizCategory", "Category")
                        .WithMany("Quizzes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.QuizAttempt", b =>
                {
                    b.HasOne("KvizHub.Repository.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KvizHub.Repository.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.UserAnswer", b =>
                {
                    b.HasOne("KvizHub.Repository.Models.Answer", null)
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId");

                    b.HasOne("KvizHub.Repository.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KvizHub.Repository.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.QuizAttempt", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.QuizCategory", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("KvizHub.Repository.Models.User", b =>
                {
                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
